# Generated by Django 3.2.20 on 2023-08-04 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclesapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='acceraltion',
            new_name='acceleration',
        ),
    ]
